---

- name: apt | Update
  apt: update_cache=yes cache_valid_time=3600
  become: true

- name: apt | Upgrade
  apt: upgrade=full

- name: apt | Install packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - atool
    - atop
    - htop
    - curl
    - wget
    - git
    - make
    - mc
    - nano
    - supervisor
    - tig
    - tree
    - vim
    - unzip
    - python3-pip
    # - ufw