
- name: Add allow rule for port 3306 to iptables
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 3306
    jump: ACCEPT
    state: present
  notify:
    - Restart the MySQL service