 
- name: MySQL | Install MySQL packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - mysql-client
    - python3-mysqldb

- name: MySQL | Start the MySQL service
  become: true
  service:
    name: mysql
    state: started
    enabled: true